sudo: required

language: generic

services:
  - docker

before_install:
  - echo "build start"
  - docker build -t hwangse/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hwangse/docker-react-app npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-472683853142"
  bucket_path: "elasticbeanstalk-ap-northeast-2-472683853142"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY
